### ISSUE TITLE
`callback` is not a function when showing "Update Published Project" prompt

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1738]
Bug introduced in 392fb9dccc4a228b21dfe88cfe415cb56a6acded

https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/publisher.js#L65-L68 <-- these lines use the `showUnpublishedChangesPrompt` function from the `publisher`'s prototype. However, the events that it is attached to send parameters that are not a callback (which is what the function actually expects) and it fails.

We should probably not use function bindings for these event listeners. Instead, let's just use closures like:
```js
bramble.on("event", function() {
  publisher.showUnpublishedChangesPrompt();
});
```

**Comment by humphd** [comment]
cc @lkisac.  Do you want to fix this for us?

**Comment by TheAlbinoPanda** [comment]
Hey ! Can I try helping out with this ? I'm new to contributing to projects , so if you could guide me through my first contribution, I would greatly appreciate it !

**Comment by gideonthomas** [comment]
@TheAlbinoPanda absolutely! If you have git installed on your computer, first try to get setup with Thimble. Our setup instructions are in the [README here](https://github.com/mozilla/thimble.mozilla.org#setupinstallation). Once you have setup Thimble (and Brackets) on your computer, you can begin working on the issue.

Let us know if you have any problems setting it up and we'd be glad to help. Once you've set up Thimble, we can help you with fixing the issue.

**Comment by lkisac** [comment]
@humphd  I would like to also help with this one if it's still ok.  If not, I believe I will be working on issue [#1737](https://github.com/mozilla/thimble.mozilla.org/issues/1737)

**Comment by humphd** [comment]
@TheAlbinoPanda I've written a blog post that walks through doing a fix in Thimble, see http://blog.humphd.org/fixing-a-bug-in-mozilla-thimble/.  It will help you.

Can I suggest that we get @Ikisac to take this particular bug, though, since it relates to a fix he's just done in a previous commit?

There's a lot to choose from in this list: https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22assigned%20to%20contributor%22%20

**Comment by TheAlbinoPanda** [comment]
Awesome ty guys @humphd @gideonthomas . I'll get to working on this tonight!

**Comment by gideonthomas** [comment]
Just gonna clarify here, @lkisac, you're working on this issue right?

@TheAlbinoPanda, if that ^ is the case, I would probably suggest working on one of these issues instead: https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22assigned%20to%20contributor%22

**Comment by humphd** [comment]
Yeah, @Ikisac is doing this one.

**Comment by lkisac** [comment]
Thanks @humphd.  Just confirming @gideonthomas I will be working on this issue.  I've started already, just getting a few errors after updating my brackets/thimble repos to the latest upstream.  Anyways, will get that sorted out and continue on this.  Thanks

**Comment by gideonthomas** [comment]
Let us know if you need any help fixing the errors after pulling the latest commits!

**Comment by lkisac** [comment]
Hi @gideonthomas.  I pulled the most recent changes just now and restarted Brackets and Thimble.  These are the errors I'm seeing:

- **CommandManager.js:195** - Attempting to register a command with a missing name, id, or command function:undefined bramble-move-file.moveFile 
- **Menu.js:582** - addMenuItem(): commandID not found: bramble-move-file.moveFile
- **bramble-menus.js:58** - Uncaught TypeError: bramble.getAllowJavaScript is not a function

**Comment by humphd** [comment]
@lkisac those errors are due to:

* issues with running a `src/` vs. `dist/` build of Brackets, and not having localized strings.  You can ignore the first 2, as they aren't a real bug
* issues in your version of the Brackets API built in `dist/bramble.js`

Both issues can be fixed by updating Brackets to upstream and calling `npm run build` before you run `npm run start` on Brackets.

**Comment by lkisac** [comment]
Thanks @humphd.  Calling `npm run build` before running `npm run start` fixed the issue in **bramble-menus.js:58**
